server:
  port: 10010
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:80 #nacos服务地址
    gateway:
      routes:
        - id: userservice #路由标识，必须唯一,   “-”开头可以设置多个
          uri: lb://userserver #负载均衡到服务器，路由的请求地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否以/user开头，如果是则符合
          #filters:
           # - AddRequestHeader=Truth,ldy hooray jvbu！
        - id: orderservice
          uri: lb://orderserver
          predicates:
            - Path=/order/**
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking awesome!

